-- ============================================================
-- RENTAL MANAGEMENT DATABASE - VIETNAM
-- MySQL 8.0+
-- Database: rental_manage_db
-- IDs: application-generated UUIDs stored compactly as BINARY(16)
-- Currency: VND
-- Charset: utf8mb4
--
-- UUID handling:
--   INSERT an application-generated UUID:
--       INSERT INTO property (property_id, ...) VALUES
--       (UUID_TO_BIN('...'), ...);
--
--
--   Read UUIDs as strings:
--       SELECT BIN_TO_UUID(property_id) AS property_id FROM property;
--
-- IDs must be generated by the application or supplied explicitly.
-- ============================================================

CREATE DATABASE IF NOT EXISTS `rental_manage_db`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE `rental_manage_db`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- 0. APPLICATION-GENERATED IDs
-- ============================================================

-- ============================================================
-- 1. ROLES / USERS
-- ============================================================

CREATE TABLE IF NOT EXISTS `role` (
    `role_id` BINARY(16) NOT NULL,
    `role_name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(500) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY (`role_id`),
    UNIQUE KEY `uq_role_name` (`role_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `user` (
    `user_id` BINARY(16) NOT NULL,
    `user_name` VARCHAR(100) NOT NULL,
    `login_email` VARCHAR(255) NOT NULL,
    `password_hash` VARCHAR(255) NULL,
    `auth_provider` VARCHAR(50) NULL,
    `auth_provider_id` VARCHAR(255) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`user_id`),
    UNIQUE KEY `uq_user_login_email` (`login_email`),
    UNIQUE KEY `uq_user_auth_provider`
        (`auth_provider`, `auth_provider_id`),
    KEY `idx_user_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `user_role` (
    `user_id` BINARY(16) NOT NULL,
    `role_id` BINARY(16) NOT NULL,
    PRIMARY KEY (`user_id`, `role_id`),

    CONSTRAINT `fk_user_role_user`
        FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `fk_user_role_role`
        FOREIGN KEY (`role_id`) REFERENCES `role` (`role_id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 2. PROPERTY / ROOM
-- ============================================================

CREATE TABLE IF NOT EXISTS `property` (
    `property_id` BINARY(16) NOT NULL,
    `property_code` VARCHAR(50) NOT NULL,
    `address_line` VARCHAR(255) NOT NULL,
    `ward_name` VARCHAR(100) NULL,
    `district_name` VARCHAR(100) NULL,
    `province_name` VARCHAR(100) NOT NULL,
    `description` TEXT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`property_id`),
    UNIQUE KEY `uq_property_code` (`property_code`),
    KEY `idx_property_location`
        (`province_name`, `district_name`, `ward_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `room` (
    `room_id` BINARY(16) NOT NULL,
    `property_id` BINARY(16) NOT NULL,
    `room_code` VARCHAR(50) NOT NULL,
    `room_name` VARCHAR(100) NULL,
    `floor` INT NULL,
    `area_m2` DECIMAL(10,2) NULL,
    `max_occupants` INT NOT NULL DEFAULT 1,
    `rent_price` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND/month',
    `room_status` VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    `description` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`room_id`),
    UNIQUE KEY `uq_room_property_code` (`property_id`, `room_code`),
    KEY `idx_room_property_id` (`property_id`),
    KEY `idx_room_status` (`room_status`),

    CONSTRAINT `fk_room_property`
        FOREIGN KEY (`property_id`) REFERENCES `property` (`property_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `ck_room_area`
        CHECK (`area_m2` IS NULL OR `area_m2` >= 0),

    CONSTRAINT `ck_room_max_occupants`
        CHECK (`max_occupants` > 0),

    CONSTRAINT `ck_room_rent_price`
        CHECK (`rent_price` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `room_image` (
    `image_id` BINARY(16) NOT NULL,
    `room_id` BINARY(16) NOT NULL,
    `image_url` TEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`image_id`),
    KEY `idx_room_image_room_id` (`room_id`),

    CONSTRAINT `fk_room_image_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 3. TENANTS
-- Vietnamese-specific identity data.
-- CCCD is stored as VARCHAR because it is an identifier, not a number.
-- ============================================================

CREATE TABLE IF NOT EXISTS `tenant` (
    `tenant_id` BINARY(16) NOT NULL,
    `user_id` BINARY(16) NOT NULL,
    `room_id` BINARY(16) NULL,

    `full_name` VARCHAR(255) NOT NULL,
    `date_of_birth` DATE NULL,
    `phone` VARCHAR(20) NULL,
    `email` VARCHAR(255) NULL,
    `gender` VARCHAR(30) NULL,
    `avatar_url` TEXT NULL,

    `identity_type` VARCHAR(30) NULL COMMENT 'CCCD / PASSPORT / OTHER',
    `identity_number` VARCHAR(30) NULL,
    `identity_issued_date` DATE NULL,
    `identity_issued_place` VARCHAR(255) NULL,

    `permanent_address` TEXT NULL,
    `emergency_contact_name` VARCHAR(255) NULL,
    `emergency_contact_phone` VARCHAR(20) NULL,

    `additional_note` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`tenant_id`),
    UNIQUE KEY `uq_tenant_user_id` (`user_id`),
    UNIQUE KEY `uq_tenant_identity`
        (`identity_type`, `identity_number`),
    KEY `idx_tenant_room_id` (`room_id`),
    KEY `idx_tenant_phone` (`phone`),
    KEY `idx_tenant_full_name` (`full_name`),

    CONSTRAINT `fk_tenant_user`
        FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `fk_tenant_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 4. RENTAL CONTRACTS
-- Monetary values are VND.
-- ============================================================

CREATE TABLE IF NOT EXISTS `rental_contracts` (
    `contract_id` BINARY(16) NOT NULL,
    `room_id` BINARY(16) NOT NULL,

    `start_date` DATE NOT NULL,
    `end_date` DATE NULL,
    `signed_at` DATETIME(3) NULL,

    `rent_amount` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND/month',
    `deposit_required` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND',

    `billing_day` TINYINT UNSIGNED NULL,
    `payment_due_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0,

    `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    `terms` TEXT NULL,
    `document_url` TEXT NULL,

    `terminated_at` DATETIME(3) NULL,
    `termination_reason` VARCHAR(500) NULL,

    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`contract_id`),
    KEY `idx_contract_room_id` (`room_id`),
    KEY `idx_contract_status` (`status`),
    KEY `idx_contract_dates` (`start_date`, `end_date`),

    CONSTRAINT `fk_contract_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `ck_contract_dates`
        CHECK (`end_date` IS NULL OR `end_date` >= `start_date`),

    CONSTRAINT `ck_contract_rent`
        CHECK (`rent_amount` >= 0),

    CONSTRAINT `ck_contract_deposit`
        CHECK (`deposit_required` >= 0),

    CONSTRAINT `ck_contract_billing_day`
        CHECK (`billing_day` IS NULL OR `billing_day` BETWEEN 1 AND 31)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `contract_tenants` (
    `contract_id` BINARY(16) NOT NULL,
    `tenant_id` BINARY(16) NOT NULL,
    `is_representative` BOOLEAN NOT NULL DEFAULT FALSE,
    `move_in_date` DATE NULL,
    `move_out_date` DATE NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`contract_id`, `tenant_id`),
    KEY `idx_contract_tenants_tenant_id` (`tenant_id`),
    KEY `idx_contract_tenants_status` (`status`),

    CONSTRAINT `fk_contract_tenant_contract`
        FOREIGN KEY (`contract_id`) REFERENCES `rental_contracts` (`contract_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `fk_contract_tenant_tenant`
        FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`tenant_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `ck_contract_tenant_dates`
        CHECK (
            `move_out_date` IS NULL
            OR `move_in_date` IS NULL
            OR `move_out_date` >= `move_in_date`
        )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 5. ANNOUNCEMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS `announcement` (
    `announcement_id` BINARY(16) NOT NULL,
    `user_id` BINARY(16) NOT NULL,
    `content` TEXT NOT NULL,
    `announcement_type` VARCHAR(50) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    `sent_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`announcement_id`),
    KEY `idx_announcement_user_id` (`user_id`),
    KEY `idx_announcement_status` (`status`),

    CONSTRAINT `fk_announcement_user`
        FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 6. PROFILE INITIALS REQUEST
-- ============================================================

CREATE TABLE IF NOT EXISTS `profile_initials_request` (
    `request_id` BINARY(16) NOT NULL,
    `tenant_id` BINARY(16) NOT NULL,
    `user_id` BINARY(16) NOT NULL,
    `request_code` VARCHAR(100) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expires_at` DATETIME(3) NULL,
    `revoked_at` DATETIME(3) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    PRIMARY KEY (`request_id`),
    UNIQUE KEY `uq_profile_request_code` (`request_code`),
    KEY `idx_profile_request_tenant_id` (`tenant_id`),
    KEY `idx_profile_request_user_id` (`user_id`),

    CONSTRAINT `fk_profile_request_tenant`
        FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`tenant_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `fk_profile_request_user`
        FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 7. SERVICES
-- Vietnam-oriented examples:
--   Điện       | kWh       | METER
--   Nước       | m3        | METER
--   Internet   | tháng     | FIXED
--   Vệ sinh    | tháng     | FIXED
--   Giữ xe     | xe/tháng | FIXED
-- ============================================================

CREATE TABLE IF NOT EXISTS `service` (
    `service_id` BINARY(16) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `unit` VARCHAR(50) NOT NULL,
    `calculation_method` VARCHAR(50) NOT NULL,
    `default_unit_price` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND/unit',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`service_id`),
    UNIQUE KEY `uq_service_name` (`name`),

    CONSTRAINT `ck_service_price`
        CHECK (`default_unit_price` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `room_service` (
    `room_id` BINARY(16) NOT NULL,
    `service_id` BINARY(16) NOT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`room_id`, `service_id`),
    KEY `idx_room_service_service_id` (`service_id`),

    CONSTRAINT `fk_room_service_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `fk_room_service_service`
        FOREIGN KEY (`service_id`) REFERENCES `service` (`service_id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 8. METERS
-- Electricity / water readings.
-- ============================================================

CREATE TABLE IF NOT EXISTS `meter` (
    `meter_id` BINARY(16) NOT NULL,
    `room_id` BINARY(16) NOT NULL,
    `meter_type` VARCHAR(50) NOT NULL COMMENT 'ELECTRICITY / WATER',
    `reading_at` DATETIME(3) NOT NULL,
    `reading_value` DECIMAL(15,3) NOT NULL,
    `evidence_url` TEXT NULL,
    `note` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`meter_id`),
    KEY `idx_meter_room_type_date`
        (`room_id`, `meter_type`, `reading_at`),

    CONSTRAINT `fk_meter_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `ck_meter_reading`
        CHECK (`reading_value` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 9. MAINTENANCE REQUESTS
-- ============================================================

CREATE TABLE IF NOT EXISTS `maintenance_requests` (
    `request_id` BINARY(16) NOT NULL,
    `room_id` BINARY(16) NOT NULL,
    `tenant_id` BINARY(16) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `priority` VARCHAR(30) NOT NULL DEFAULT 'NORMAL',
    `status` VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),
    `completed_at` DATETIME(3) NULL,

    PRIMARY KEY (`request_id`),
    KEY `idx_maintenance_room_id` (`room_id`),
    KEY `idx_maintenance_tenant_id` (`tenant_id`),
    KEY `idx_maintenance_status` (`status`),

    CONSTRAINT `fk_maintenance_room`
        FOREIGN KEY (`room_id`) REFERENCES `room` (`room_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `fk_maintenance_tenant`
        FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`tenant_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `request_image` (
    `image_id` BINARY(16) NOT NULL,
    `request_id` BINARY(16) NOT NULL,
    `file_url` TEXT NOT NULL,
    `image_type` VARCHAR(50) NULL,

    PRIMARY KEY (`image_id`),
    KEY `idx_request_image_request_id` (`request_id`),

    CONSTRAINT `fk_request_image_request`
        FOREIGN KEY (`request_id`) REFERENCES `maintenance_requests` (`request_id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 10. INVOICES
-- All monetary amounts are VND.
-- ============================================================

CREATE TABLE IF NOT EXISTS `invoice` (
    `invoice_id` BINARY(16) NOT NULL,
    `invoice_number` VARCHAR(100) NOT NULL,
    `issued_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `due_date` DATE NULL,

    `subtotal` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND',
    `discount_amount` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND',
    `tax_amount` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND',
    `total_amount` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND',

    `note` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`invoice_id`),
    UNIQUE KEY `uq_invoice_number` (`invoice_number`),
    KEY `idx_invoice_due_date` (`due_date`),
    KEY `idx_invoice_issued_at` (`issued_at`),

    CONSTRAINT `ck_invoice_subtotal`
        CHECK (`subtotal` >= 0),
    CONSTRAINT `ck_invoice_discount`
        CHECK (`discount_amount` >= 0),
    CONSTRAINT `ck_invoice_tax`
        CHECK (`tax_amount` >= 0),
    CONSTRAINT `ck_invoice_total`
        CHECK (`total_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `invoice_item` (
    `item_id` BINARY(16) NOT NULL,
    `invoice_id` BINARY(16) NOT NULL,
    `service_id` BINARY(16) NOT NULL,
    `description` VARCHAR(500) NULL,
    `unit` VARCHAR(50) NULL,
    `unit_price` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'VND/unit',
    `amount` DECIMAL(15,3) NOT NULL DEFAULT 0,

    PRIMARY KEY (`item_id`),
    KEY `idx_invoice_item_invoice_id` (`invoice_id`),
    KEY `idx_invoice_item_service_id` (`service_id`),

    CONSTRAINT `fk_invoice_item_invoice`
        FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`invoice_id`)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT `fk_invoice_item_service`
        FOREIGN KEY (`service_id`) REFERENCES `service` (`service_id`)
        ON DELETE RESTRICT ON UPDATE CASCADE,

    CONSTRAINT `ck_invoice_item_unit_price`
        CHECK (`unit_price` >= 0),
    CONSTRAINT `ck_invoice_item_amount`
        CHECK (`amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- 11. ONE REPRESENTATIVE TENANT PER CONTRACT
-- MySQL does not support a PostgreSQL-style partial unique index.
-- These triggers enforce the ERD rule.
-- ============================================================

DROP TRIGGER IF EXISTS `trg_contract_tenant_representative_insert`;
DROP TRIGGER IF EXISTS `trg_contract_tenant_representative_update`;

DELIMITER $$

CREATE TRIGGER `trg_contract_tenant_representative_insert`
BEFORE INSERT ON `contract_tenants`
FOR EACH ROW
BEGIN
    IF NEW.`is_representative` = TRUE
       AND EXISTS (
           SELECT 1
           FROM `contract_tenants`
           WHERE `contract_id` = NEW.`contract_id`
             AND `is_representative` = TRUE
       )
    THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT =
                'A rental contract can have only one representative tenant';
    END IF;
END$$

CREATE TRIGGER `trg_contract_tenant_representative_update`
BEFORE UPDATE ON `contract_tenants`
FOR EACH ROW
BEGIN
    IF NEW.`is_representative` = TRUE
       AND EXISTS (
           SELECT 1
           FROM `contract_tenants`
           WHERE `contract_id` = NEW.`contract_id`
             AND `tenant_id` <> NEW.`tenant_id`
             AND `is_representative` = TRUE
       )
    THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT =
                'A rental contract can have only one representative tenant';
    END IF;
END$$

DELIMITER ;

-- ============================================================
-- 12. INITIAL VIETNAMESE MASTER DATA
-- ============================================================

INSERT INTO `role`
    (`role_id`, `role_name`, `description`, `status`)
VALUES
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000001'), 'ADMIN', 'Quản trị hệ thống', 'ACTIVE'),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000002'), 'LANDLORD', 'Chủ nhà / người quản lý nhà trọ', 'ACTIVE'),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000003'), 'TENANT', 'Người thuê phòng', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `description` = VALUES(`description`);

INSERT INTO `service`
    (`service_id`, `name`, `unit`, `calculation_method`, `default_unit_price`)
VALUES
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000011'), 'Điện', 'kWh', 'METER', 0),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000012'), 'Nước', 'm3', 'METER', 0),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000013'), 'Internet', 'tháng', 'FIXED', 0),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000014'), 'Phí vệ sinh', 'tháng', 'FIXED', 0),
    (UUID_TO_BIN('00000000-0000-4000-8000-000000000015'), 'Phí giữ xe', 'xe/tháng', 'FIXED', 0)
ON DUPLICATE KEY UPDATE
    `unit` = VALUES(`unit`),
    `calculation_method` = VALUES(`calculation_method`);

-- ============================================================
-- 13. EXAMPLES
-- ============================================================

-- IDs must be supplied by the application:
--
-- INSERT INTO `property`
--     (`property_id`, `property_code`, `address_line`, `province_name`)
-- VALUES
--     (UUID_TO_BIN('...'), 'PT001', '123 Đường X', 'Thành phố Hồ Chí Minh');
--
-- SELECT BIN_TO_UUID(`property_id`) AS `property_id`,
--        `property_code`
-- FROM `property`;
--
-- Application-generated UUID:
--
-- INSERT INTO `property`
--     (`property_id`, `property_code`, `address_line`, `province_name`)
-- VALUES
--     (
--         UUID_TO_BIN('...'),
--         'PT002',
--         '456 Đường Y',
--         'Thành phố Hồ Chí Minh'
--     );

-- ============================================================
-- 14. IMPORTANT PRODUCTION NOTE
-- ============================================================
-- BINARY(16) is used instead of CHAR(36) to keep PK/FK indexes
-- compact and efficient.
--
-- For most backend applications, the preferred architecture is:
--   1. Generate a UUID in the application/service layer.
--   2. Convert it to BINARY(16) before INSERT.
--
-- ORM/query examples:
--   UUID_TO_BIN(?)            -- application UUID string -> BINARY(16)
--   BIN_TO_UUID(id)           -- BINARY(16) -> UUID string
--

SET FOREIGN_KEY_CHECKS = 1;
